### ISSUE TITLE
Can't install it on Mac OS X

### ISSUE THREAD

**Issue by marius92mc** [jleb/pyaudio#2]
$ pip install pyaudio
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pyaudio
  Using cached PyAudio-0.2.9.tar.gz
Installing collected packages: pyaudio
  Running setup.py install for pyaudio
    building '_portaudio' extension
    clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Qunused-arguments -Qunused-arguments -DMACOSX=1 -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/_portaudiomodule.c -o build/temp.macosx-10.10-x86_64-2.7/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found
    #include "portaudio.h"
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/7f/8wp_9bn96ls_sydktcmqlfyc0000gn/T/pip-build-CLhq5E/pyaudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/7f/8wp_9bn96ls_sydktcmqlfyc0000gn/T/pip-to1Dsi-record/install-record.txt --single-version-externally-managed --compile:
    running install

```
running build

running build_py

creating build

creating build/lib.macosx-10.10-x86_64-2.7

copying src/pyaudio.py -> build/lib.macosx-10.10-x86_64-2.7

running build_ext

building '_portaudio' extension

creating build/temp.macosx-10.10-x86_64-2.7

creating build/temp.macosx-10.10-x86_64-2.7/src

clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Qunused-arguments -Qunused-arguments -DMACOSX=1 -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/_portaudiomodule.c -o build/temp.macosx-10.10-x86_64-2.7/src/_portaudiomodule.o

src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found

#include "portaudio.h"

         ^

1 error generated.

error: command 'clang' failed with exit status 1

----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/7f/8wp_9bn96ls_sydktcmqlfyc0000gn/T/pip-build-CLhq5E/pyaudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/7f/8wp_9bn96ls_sydktcmqlfyc0000gn/T/pip-to1Dsi-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/7f/8wp_9bn96ls_sydktcmqlfyc0000gn/T/pip-build-CLhq5E/pyaudio
```

**Comment by coveloper** [comment]
I have same problem

**Comment by AndrewHamm** [comment]
`$ pip install --global-option='build_ext' --global-option='-I/usr/local/include' --global-option='-L/usr/local/lib' pyaudio` 
(src: http://stackoverflow.com/a/33821084/3715871)

This answer allowed me to install it, but I am just running in to even more problems when trying to use it.

**Comment by NilanjPatel** [comment]
it says already installed , but when i run my code 
"
Traceback (most recent call last):
  File "/Users/Nilanj/AI-Smart-Mirror/hhsmartmirror/lib/python3.5/site-packages/speech_recognition/__init__.py", line 83, in get_pyaudio
    import pyaudio
ImportError: No module named 'pyaudio'
"

**Comment by BridgeNB** [comment]
My solution would be 
brew install portaudio
pip install pyaudio
That solved my installation issue.

**Comment by jleb** [comment]
Hello,

Please note that I am not the author of pyaudio, and this is GitHub repo is *not* the canonical source. The correct website is http://people.csail.mit.edu/hubert/pyaudio/. Please check there for the latest version, as well as instructions for support and contributions.
