### ISSUE TITLE
Cannot detect USB mic, but it detects after plug it in again.

### ISSUE THREAD

**Issue by openedhardware** [jleb/pyaudio#5]
At first time, pyaud.get_device_info_by_index function does not detect my USB mic.

Here is my python code

```
import pyaudio
p = pyaudio.PyAudio()
for i in range(p.get_device_count()):
  dev = p.get_device_info_by_index(i)
  print((i,dev['name'],dev['maxInputChannels']))
```

And here is the result:

```
(0, u'bcm2835 ALSA: - (hw:0,0)', 0L)
(1, u'bcm2835 ALSA: IEC958/HDMI (hw:0,1)', 0L)
(2, u'default', 0L)
```

And I just tried to check whether my mic is detected or not
```
 $ lsusb
Bus 001 Device 004: ID 0d8c:013c C-Media Electronics, Inc. CM108 Audio Controller
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
As you could see, USB mic is detected.

After removing my USB mic and plug it again;

```
(0, u'bcm2835 ALSA: - (hw:0,0)', 0L)
(1, u'bcm2835 ALSA: IEC958/HDMI (hw:0,1)', 0L)
(2, u'USB PnP Sound Device: Audio (hw:1,0)', 1L)
(3, u'sysdefault', 128L)
(4, u'spdif', 1L)
(5, u'default', 0L)
```

Any idea?

**Comment by jleb** [comment]
Hello,

Please note that I am not the author of pyaudio, and this is GitHub repo is *not* the canonical source. The correct website is http://people.csail.mit.edu/hubert/pyaudio/. Please check there for the latest version, as well as instructions for support and contributions.
